/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tarea1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cris
 */
public class Main extends javax.swing.JFrame {
    
    HashMap Libros = new HashMap();
    Set<Integer> keys = Libros.keySet();
    Boolean sell = false;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocation(0, 0);
        setSize(700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Agregar Libro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 23, 72, 16);

        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1InputMethodTextChanged(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(22, 46, 112, 33);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(32, 92, 72, 22);

        jLabel4.setText("Alquilados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 260, 170, 30);

        jLabel5.setText("Vendidos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 170, 30);

        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(30, 200, 70, 40);

        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 300, 70, 50);

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 310, 120, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Alquilar");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 270, 64, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Comprar");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(280, 240, 160, 20);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 80, 169, 146);

        jLabel2.setText("Lista de libros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 40, 72, 16);

        jTextField2.setEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(510, 80, 80, 30);

        jLabel3.setText("Cantidad total de libros:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 40, 160, 30);

        jLabel6.setText("Disponibles");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 150, 90, 40);

        jTextField5.setEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(510, 200, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int cant = (int) Math.floor((int)(Math.random()*(10-2+1)));
        System.out.println(cant);
     String data = jTextField1.getText();
    if (data.length() == 0) {
        JOptionPane.showMessageDialog(null, "Nombre del Libro vacio", "" ,JOptionPane.WARNING_MESSAGE);
    } else {
    jTextField1.setText("");
    HashMap dic = new HashMap();
    dic.put("Nombre",data);
    dic.put("Cantidad", cant);
    dic.put("Vendidos", 0);
    dic.put("Alquilados", 0);
    
    Libros.put(((int)Libros.size()+1), dic);
    datosConvert(Libros);

    // TODO add your handling code here:
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void datosConvert(HashMap data) {
        String[] list = new String[data.size()+1];

        
        for (Integer key : keys) {
            HashMap dato = (HashMap) data.get(key);
            list[key] = dato.get("Nombre").toString();
        }
        /*for (int i = 0; i < data.size(); i++) {
            Object dato = data;
            System.out.println(dato);
            list[i] = dato.toString();
        } */
        
        jList1.setListData(list);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1InputMethodTextChanged
           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1InputMethodTextChanged

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PropertyChange

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
               // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int libroSel = jList1.getSelectedIndex();
        if (libroSel == -1) {

         JOptionPane.showMessageDialog(null, "Debe seleccionar un libro a catalogar", "" ,JOptionPane.WARNING_MESSAGE);
         buttonGroup1.clearSelection();
         
        } else {
        HashMap dato = (HashMap) Libros.get(libroSel);
        Boolean dips = calculate(dato);
         if (jRadioButton1.isSelected() == false &&
                (jRadioButton2.isSelected() == false)){
        JOptionPane.showMessageDialog(null, "Debe seleccionar una accion", "" ,JOptionPane.WARNING_MESSAGE);
        buttonGroup1.clearSelection();
        } else if (dips == false) {
          JOptionPane.showMessageDialog(null, "No hay mas libros disponibles", "" ,JOptionPane.WARNING_MESSAGE);
        buttonGroup1.clearSelection();   
        } else {
        Update(libroSel);
        buttonGroup1.clearSelection();
        }
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
      
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

        String cantLibros = "";
        HashMap data = (HashMap) Libros.get(jList1.getSelectedIndex());
        if (data != null) {
            System.out.println(data);
            calculate(data);
            cantLibros = data.get("Cantidad").toString();
            jTextField2.setText(cantLibros);
            changeTField(data);
        } else {
        jTextField5.setText("");
        jTextField4.setText("");
        jTextField3.setText("");
        jTextField2.setText("");
        }

                // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped

    
    private void Update(int indx) {
        check();
        

            HashMap dato = (HashMap) Libros.get(indx);
            int alq = (int) dato.get("Alquilados"); 
            int vend = (int) dato.get("Vendidos");
            if (sell == true) {
                dato.put("Vendidos", (vend + 1));
                
            } else if (sell == false) {
                dato.put("Alquilados", (alq + 1));
                
            }
            changeTField(dato);
        
    }
    
    
    private void changeTField(HashMap dato) {
        jTextField3.setText(dato.get("Vendidos").toString());
        jTextField4.setText(dato.get("Alquilados").toString());
        calculate(dato);
    }
    
    private boolean calculate(HashMap dato) {
        Boolean valor = true;
        int cantidad = (int)dato.get("Cantidad");
        int Alquilados = (int)dato.get("Alquilados");
        int Vendidos = (int)dato.get("Vendidos");
            System.out.println(cantidad);
            System.out.println(Alquilados);
            System.out.println(Vendidos);
       int disponible =  (cantidad-(Alquilados + Vendidos));    
            System.out.println(disponible);
        if (disponible <= 0) {
            disponible = 0;
            jTextField5.setText(String.valueOf(disponible));
            valor = false;
        } else {
            jTextField5.setText(String.valueOf(disponible));
            valor = true;
        }
       return valor;
   
    }
    
    private void check () {
        if (jRadioButton1.isSelected()) {
            sell = true;
        } else if (jRadioButton2.isSelected()) {
            sell = false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
